### ISSUE TITLE
Nil Value

### ISSUE THREAD

**Issue by Belorico** [qbcore-framework/qb-vehiclekeys#100]
Getting this on console:

![image](https://user-images.githubusercontent.com/4929196/163293904-f81898d3-07ed-4d0d-a68d-5eaab84c9d45.png)

**Comment by Andyauk** [comment]
Is it a stolen car, as I think it's when you don't actually own the car/keys. Something like that, I've seen it before.

**Comment by ItsANoBrainer** [comment]
Need reproduction steps, this does not happen to me.

**Comment by Belorico** [comment]
It happens everytime i join the server.  On server console. Downloaded last version again, deleted all vehicles on player_vehicles table. Same thing

**Comment by Belorico** [comment]
Fixed

**Comment by a3rgames** [comment]
how?
