### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Nelydde** [qbcore-framework/qb-vehiclekeys#101]
When a player opens his car for me to get in, in the driver's seat. I can't get in, like the vehicle is closed.

**Comment by Nelydde** [comment]
When player use /givekeys, nothing happens, I need to use the admin command : /givecarkeys ID Plate

**Comment by tom-osborne** [comment]
`/givekeys` should work fine. It should give keys to the ID you give in the command, or the nearest person if you did not give an ID. You need to be looking at the vehicle so the script knows which keys to give.
If you are sitting in the vehicle, it will give keys to all people in the vehicle with you. 

If you have further issues with this, please raise a new issue giving evidence of any errors and steps to replicate the error. Thanks
