### ISSUE TITLE
How to change Car Lockpick Minigame ?? there is No option to change !!

### ISSUE THREAD

**Issue by subhampro** [qbcore-framework/qb-vehiclekeys#105]
![image](https://user-images.githubusercontent.com/33375250/165885447-420b3246-d007-4a8d-a3f0-48b361def562.png)

There is no option I can find with it !!!

**Comment by ItsANoBrainer** [comment]
The option is in the code, change the minigame, there is no "config option" to do so. Learn to code.

**Comment by ItsANoBrainer** [comment]
Join the qbcore discord and open a support thread to get assistance learning things like this.

**Comment by subhampro** [comment]
> The option is in the code, change the minigame, there is no "config option" to do so. Learn to code.

are you asking me to change  qb-keyminigame ?
