### ISSUE TITLE
[BUG] - No need to search vehicle

### ISSUE THREAD

**Issue by Griefa** [qbcore-framework/qb-vehiclekeys#110]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to a randomly parked vehicle on the street
2. Lockpick the door/hop in and wait for the "wiring" animation to complete. Half the time the option to search for keys doesnt even appear
3. You will then have full access to the vehicle without searching the vehicle for keys

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones?Not relevant here
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by tom-osborne** [comment]
This is now fixed
