### ISSUE TITLE
[SUGGESTION] Increase distance for locking

### ISSUE THREAD

**Issue by L1quidSn4ke** [qbcore-framework/qb-vehiclekeys#115]
Currently you must be touching the car to lock it, however I'd like to lock it from a step or two away.
If there is a line of code that I can add or change then please direct me to it.

**Comment by tom-osborne** [comment]
Hi @L1quidSn4ke the script uses three ray casts to detect the vehicle. Currently, the ray casts used is shown here: https://i.imgur.com/FRED0kV.png
So you need to be quite close to the vehicle for these to hit the vehicle. You could try adjusting the offsets in `qb-vehiclekeys / client / main.lua`

```lua
    local RaycastOffsetTable = {
        { ['fromOffset'] = vector3(0.0, 0.0, 0.0), ['toOffset'] = vector3(0.0, 20.0, -10.0) }, -- Waist to ground 45 degree angle
        { ['fromOffset'] = vector3(0.0, 0.0, 0.7), ['toOffset'] = vector3(0.0, 10.0, -10.0) }, -- Head to ground 30 degree angle
        { ['fromOffset'] = vector3(0.0, 0.0, 0.7), ['toOffset'] = vector3(0.0, 10.0, -20.0) }, -- Head to ground 15 degree angle
    }
```
I don't have any preset numbers to give you, so you probably need to use trial and error to adjust them.

**Comment by L1quidSn4ke** [comment]
This doesn't make sense. How is this going to unlock/lock the car further from the vehicle?

**Comment by tom-osborne** [comment]
By making the raycast longer. You would still have to be facing the vehicle though.

You could try making it toggle locks based on the closest vehicle, but it could get messy when there are lots of cars around.
