### ISSUE TITLE
[SUGGESTION] option to share keys with a player

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-vehiclekeys#116]
Please add a feature to share keys with a player so a friend can drive without having to look for keys

**Comment by nggcasey** [comment]
Tried /givekey?

**Comment by LightUpFam** [comment]
Yes.  /givekeys only seems worth with NPC cars. 

Player imports don't share key

**Comment by tom-osborne** [comment]
@LightUpFam `/givekeys` will work for any vehicle.

There are three scenarios by which you can give a player keys using the `/givekeys` command
1. You give keys to a player with a specific `id` by using `/givekeys [id]`
2. You give keys to the closest player by using `/givekeys` when standing outside of the vehicle. You must stand next to and be facing the vehicle for this to work.
3. You give keys to all players sat in the vehicle by using `/givekeys` while also being sat in the vehicle.
