### ISSUE TITLE
[BUG] not able to lock or unlock vehicles

### ISSUE THREAD

**Issue by ggoodell2** [qbcore-framework/qb-vehiclekeys#118]
as soon as anyone loads into my server they get this error in the f8 console.
https://gyazo.com/d59c024b0bac1fb2b15325c26e6cbf22
restart does the same thing.

**Comment by tom-osborne** [comment]
@ggoodell2 Please test on the latest version. That error doesn't seem to match the latest version, so hopefully updating will fix your issue.

Please raise a new issue if you still encounter problems.
