### ISSUE TITLE
[BUG] Lockpick do not break when failing lockpicking a car

### ISSUE THREAD

**Issue by ChapiChapi** [qbcore-framework/qb-vehiclekeys#120]
For some reason the lockpick does not break when you fail a lockpick, i see that the event triggered to break the lockpick is:

TriggerServerEvent("inventory:server:breakLockpick", "lockpick")

But for some reason that event is not in the inventory and i cant find it

**Comment by tom-osborne** [comment]
Update your `qb-vehiclekeys` please.
The event used to break the lock pick is as follows:
```lua
TriggerServerEvent("qb-vehiclekeys:server:breakLockpick", "advancedlockpick")
```
or 
```lua
TriggerServerEvent("qb-vehiclekeys:server:breakLockpick", "lockpick")
```
