### ISSUE TITLE
[SUGGESTION] Unlock command for LEO

### ISSUE THREAD

**Issue by MidnightGamingNetwork** [qbcore-framework/qb-vehiclekeys#121]
**Is your feature request related to a problem? Please describe.**
When police are on a traffic stop, police do not have a way to unlock a vehicle to search it. Police have to OOC tell the player to give them the keys to the vehicle. 

**Describe the feature you'd like**
It would be cool if police had a command that will allow them to unlock players vehicles.

**Comment by Xodus989** [comment]
This issue doesn't fix the bug, but it allows cops to get into the vehicle and at least search it by using a lockpick & bypassing all the animation & searching for keys. I added stuff starting at    local player = QBCore.Functions.GetPlayerData() until the usingAdvanced.

`function LockpickDoor(isAdvanced)
    local ped = PlayerPedId()
    local pos = GetEntityCoords(ped)
    local vehicle = QBCore.Functions.GetClosestVehicle()

    if vehicle == nil or vehicle == 0 then return end
    if HasKeys(QBCore.Functions.GetPlate(vehicle)) then return end
    if #(pos - GetEntityCoords(vehicle)) > 2.5 then return end
    if GetVehicleDoorLockStatus(vehicle) <= 0 then return end

    local player = QBCore.Functions.GetPlayerData()
    PlayerJob = player.job

    if PlayerJob.name == "police" then
        SetVehicleDoorsLocked(vehicle, 1)
        TriggerServerEvent('qb-vehiclekeys:server:AcquireVehicleKeys', QBCore.Functions.GetPlate(vehicle))
        return
    end

    usingAdvanced = isAdvanced
    TriggerEvent('qb-lockpick:client:openLockpick', lockpickFinish)
end`

**Comment by nzkfc** [comment]
> 

Sorry wehere does this go? the formatting is a bit borked on github

**Comment by nzkfc** [comment]
> 

Hey man, this might need a review if possible?

**Comment by nzkfc** [comment]
> @nzkfc Rather than using `SetVehicleDoorsLocked()` you should use the following event:
> 
> ```lua
> TriggerServerEvent('qb-vehiclekeys:server:setVehLockState', NetworkGetNetworkIdFromEntity(vehicle), 1)
> ```

Thanks that works, would be cool to add a progress bar and clipboard animation or some sort of mechanic animation, then also enable an item other then advanced lock picks to add to police armory.

Something to consider for this suggstion I guess :)

**Comment by ahmed608** [comment]
Thanks for your suggestion, I'll see this and get it working and testing it
