### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-vehiclekeys#123]
drive around in your car, lock it, go inside somewhere, when you go back to car, the unlock animation happens and soun but the car stays locked.  

Also the /givekey function doesnt work as intended

**Comment by tom-osborne** [comment]
@LightUpFam Please try with latest update. Make sure you are facing the vehicle when locking/unlocking.

What about the `/givekeys` command does not work? How exactly are you using it?
