### ISSUE TITLE
[SUGGESTION] Additional Configs (locked player cars vs parked AI)

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-vehiclekeys#126]
**Is your feature request related to a problem? Please describe.**
Sort of, can't unlock all cars by default without excluding player-owned cars.

**Describe the feature you'd like**
Currently the default setting is that you lockpick open a car and then hot-wire it. It would be nice to have a config that allows for door state to be unlocked for all AI driven and parked cards, however allow for hot-wiring still.

Issue at the moment is we can almost achieve this, however parked player-owned cars end up being unlocked also due to [this line](https://github.com/qbcore-framework/qb-vehiclekeys/blob/a0691fb0ed5ac80260a182983cf8f0d8034bfd7b/client/main.lua#L58).
If you set the next line (59) to 1.

**Describe alternatives you've considered**
Nope

**Additional context**
I'm sure it's a matter of looking up a plate and returning that it is "player owned" and then setting state to 2, otherwise 1. I'm just not skilled enough to work through it.

**Comment by tom-osborne** [comment]
@nzkfc Try out the latest version. I think it covers your request.
