### ISSUE TITLE
Stealing parked cars does not require you to use lockpick to hotwire the car

### ISSUE THREAD

**Issue by mirrox1337** [qbcore-framework/qb-vehiclekeys#13]
Works when stealing cars from npc

**Comment by darknight2590** [comment]
i have this problem

**Comment by darknight2590** [comment]
When the vehicle is parked on the side of the street
You enter car and start the vehicle
without using lockpick or hotware or any etc

**Comment by BerkieBb** [comment]
Fixing this now

**Comment by vanillla1** [comment]
I'm sorry
But it has been tested
And the problem is still
You can steal parked vehicles without lockpick
@BerkieBb

**Comment by BerkieBb** [comment]
I said I'm fixing it, not I fixed it
