### ISSUE TITLE
[BUG] When car is spawned trough garage, it will not give me keys

### ISSUE THREAD

**Issue by itsP33t** [qbcore-framework/qb-vehiclekeys#131]
**Describe the bug**
When I spawn a vehicle through the garage it doesn't give me the keys or teleport me to the vehicle.

**To Reproduce**
1. Go to garage and spawn any vehicle

**Expected behavior**
You should be teleported to the vehicle and there should be notification that you got the keys to the vehicle

**Screenshots**
https://cdn.discordapp.com/attachments/912726392557432842/1004441907956555806/2022-08-03_19-26-29.mp4
https://cdn.discordapp.com/attachments/912726392557432842/1004442474183409664/unknown.png

**Questions (please complete the following information):**
 - When you last updated: Yesterday (2.8)
 - Are you using custom resource? which ones? zdiscord and many more, but no resource is doing anything with the keys
 - Have you renamed `qb-` to something custom? no

**Comment by tom-osborne** [comment]
Hi @itsP33t This does not happen on latest version. 
Please update your qb-vehiclekeys script and test again. Make sure you have latest core.

**Comment by itsP33t** [comment]
it was latest when i made this issue

**Comment by tom-osborne** [comment]
> 

Do you also have an up to date qb-core?

**Comment by itsP33t** [comment]
yes i do, updated all scripts. To fix it i needed to download like 2 commits older version.
