### ISSUE TITLE
[BUG] not receiving vehicle keys

### ISSUE THREAD

**Issue by Smitthyy** [qbcore-framework/qb-vehiclekeys#139]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

Vehicles when purchased through the vehicle shop or when obtained for a job, notification received states 'you get keys to the vehicle' but the vehicle spawns with me inside and I must search for keys.

**To Reproduce**
1. Go to 'vehicle shop or job'
2. Click on 'any vehicle to buy or get with your job'
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
Buy vehicle. receive keys, use vehicle

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: fresh TxAdmin today, new qb-policejob, qb-vehiclekeys, qb-core today.
 - Are you using custom resource? which ones? No.
 - Have you renamed `qb-` to something custom? No.

**Additional context**
This works as expected on my windows localhost dev server. It does not work on my Linux VPS live environment. Everything else works as expected in both environments. Copying the exact files from localhos to live also does not make any difference to the outcome.

**Comment by LateNightRP** [comment]
Having the same issue as well. Updated Vehicle Keys and Vehicle Shop on Monday (8-8-22). When players buy a vehicle it will not give them keys to the vehicle. It shows that they own it in the sql and the phone, but its just not giving them the keys to their owned vehicle for some odd reason. Not sure what update was done to this.

**Comment by tom-osborne** [comment]
Any errors for this in client or server console?

**Comment by Smitthyy** [comment]
In the end it turned out to be another resource that was changing the numberplate on cars. I assume the keys system works with numberplate somehow so it was issuing the keys to the car but because the other resource was assigning it a different plate I guess it wasn't working? This resource was within a different folder so missed it when I initially stopped all my other resources to figure it out the first time.

**Comment by GetBackJames** [comment]
smitthy if you don't mind what ended up being the recourse causing this issue as we are having the same problem and cannot source the problem.

**Comment by samabergh** [comment]
Hi i am having this too. can you please tell me what resource it was ? would be much appreciated.

**Comment by samabergh** [comment]
> Hi i am having this too. can you please tell me what resource it was ? would be much appreciated.

Hi i am having this too. can you please tell me what resource it was ? would be much appreciated.

**Comment by samabergh** [comment]
> In the end it turned out to be another resource that was changing the numberplate on cars. I assume the keys system works with numberplate somehow so it was issuing the keys to the car but because the other resource was assigning it a different plate I guess it wasn't working? This resource was within a different folder so missed it when I initially stopped all my other resources to figure it out the first time.

Hi i am having this too. can you please tell me what resource it was ? would be much appreciated.

**Comment by Smitthyy** [comment]
Sorry guys it was an obvious one it was literally called BritishNumberplates. It was just hidden within another folder so I didn't realise it was still starting while I was troubleshooting.
