### ISSUE TITLE
[BUG] All weapons except SMG's work for  carjacking

### ISSUE THREAD

**Issue by TheNotourius** [qbcore-framework/qb-vehiclekeys#140]
SMG's as a whole do not work for carjacking all other weapons work i think it has something todo with hash thats used in CarJackChance table.

Hopefully their is a solution as i have tried for acouple fo days and no joy!

Thank you for the fantastic resource.

**Comment by Z3rio** [comment]
Hello, this seems to work for me upon testing the script. Please ensure that you are using the newest version.
And if it still doesnt work then please tell me exactly which weapon you are using since there are more then 1 SMG.
