### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KSJDiamondGaming** [qbcore-framework/qb-vehiclekeys#144]
MainThrd/ Creating script environments for qb-vehiclekeys
[    955766] [b2372_GTAProce]             MainThrd/ Error parsing script @qb-vehiclekeys/client/main.lua in resource qb-vehiclekeys: @qb-vehiclekeys/client/main.lua:69: 'end' expected (to close 'for' at line 65) near 'elseif'
[    955766] [b2372_GTAProce]             MainThrd/ Failed to load script client/main.lua.
[    955782] [b2372_GTAProce]             MainThrd/ OnConnectionProgress: Mounted qb-vehiclekeys (1 of 1)

**Comment by tom-osborne** [comment]
@KSJDiamondGaming Please take a fresh download of the latest version and re-test.

**Comment by KSJDiamondGaming** [comment]
It was the latest as of 3.30 today but another version has fixed this. thanks

**Comment by tom-osborne** [comment]
Great, glad to hear it's fixed. Thanks for the feedback
