### ISSUE TITLE
Can't unlock door car (losing keys)

### ISSUE THREAD

**Issue by p4zinee** [qbcore-framework/qb-vehiclekeys#15]
if you get your vehicle out of your garage, the vehicle key works, but if you locked the door and get in any other player vehicle or NPC vehicle, and you try to get back to your vehicle, you don't have the keys anymore and can't unlock the door. 
here for example : 
https://www.youtube.com/watch?v=pdu4mQFZu6c&feature=youtu.be

**Comment by BerkieBb** [comment]
Fixing this now
