### ISSUE TITLE
[BUG] Keys Bug

### ISSUE THREAD

**Issue by GabbarFramework** [qbcore-framework/qb-vehiclekeys#150]
When You Sit In A Vehicle Then Start Eating Something And Then Press H Then Cancel All Progress By Pressing ESC And Then You Will Get The Keys To All The Vehicles In The City .

Preview :- https://drive.google.com/file/d/1Ejeg9hAD5fSYQ-2jj0ZKhlSAzBHFqWxF/view?usp=sharing

**Comment by tom-osborne** [comment]
@GabbarFramework Do you see any errors in the client or server consoles when this happens? Have you made any adjustments to the config for qb-vehiclekeys?

**Comment by GabbarFramework** [comment]
@tom-osborne I Didnt Seen Any Errors And I Just Made Changes In Config And Made First Two Lines From true To false

**Comment by tom-osborne** [comment]
Can you share your config?

**Comment by GabbarFramework** [comment]
Config = {}

-- NPC Vehicle Lock States
Config.LockNPCDrivingCars = false -- Lock state for NPC cars being driven by NPCs [true = locked, false = unlocked]
Config.LockNPCParkedCars = false -- Lock state for NPC parked cars [true = locked, false = unlocked]

-- Lockpick Settings
Config.RemoveLockpickNormal = 0.5 -- Chance to remove lockpick on fail
Config.RemoveLockpickAdvanced = 0.2 -- Chance to remove advanced lockpick on fail
Config.LockPickDoorEvent = function() -- This function is called when a player attempts to lock pick a vehicle
    TriggerEvent('qb-lockpick:client:openLockpick', LockpickFinishCallback)
end

-- Carjack Settings
Config.CarjackingTime = 7500 -- How long it takes to carjack
Config.DelayBetweenCarjackings = 10000 -- Time before you can carjack again
Config.CarjackChance = {
    ['2685387236'] = 0.01, -- melee
    ['416676503'] = 0.5, -- handguns
    ['-957766203'] = 0.75, -- SMG
    ['860033945'] = 0.90, -- shotgun
    ['970310034'] = 0.90, -- assault
    ['1159398588'] = 0.99, -- LMG
    ['3082541095'] = 0.99, -- sniper
    ['2725924767'] = 0.99, -- heavy
    ['1548507267'] = 0.0, -- throwable
    ['4257178988'] = 0.01, -- misc
}

-- Hotwire Settings
Config.HotwireChance = 0.5 -- Chance for successful hotwire or not
Config.TimeBetweenHotwires = 5000 -- Time in ms between hotwire attempts
Config.minHotwireTime = 20000 -- Minimum hotwire time in ms
Config.maxHotwireTime = 40000 --  Maximum hotwire time in ms

-- Police Alert Settings
Config.AlertCooldown = 10000 -- 10 seconds
Config.PoliceAlertChance = 0.75 -- Chance of alerting police during the day
Config.PoliceNightAlertChance = 0.50 -- Chance of alerting police at night (times:01-06)

-- These vehicles cannot be jacked
Config.ImmuneVehicles = {
    'stockade'
}

-- These vehicles will never lock
Config.NoLockVehicles = {}

-- These weapons cannot be used for carjacking
Config.NoCarjackWeapons = {
    "WEAPON_UNARMED",
    "WEAPON_Knife",
    "WEAPON_Nightstick",
    "WEAPON_HAMMER",
    "WEAPON_Bat",
    "WEAPON_Crowbar",
    "WEAPON_Golfclub",
    "WEAPON_Bottle",
    "WEAPON_Dagger",
    "WEAPON_Hatchet",
    "WEAPON_KnuckleDuster",
    "WEAPON_Machete",
    "WEAPON_Flashlight",
    "WEAPON_SwitchBlade",
    "WEAPON_Poolcue",
    "WEAPON_Wrench",
    "WEAPON_Battleaxe",
    "WEAPON_Grenade",
    "WEAPON_StickyBomb",
    "WEAPON_ProximityMine",
    "WEAPON_BZGas",
    "WEAPON_Molotov",
    "WEAPON_FireExtinguisher",
    "WEAPON_PetrolCan",
    "WEAPON_Flare",
    "WEAPON_Ball",
    "WEAPON_Snowball",
    "WEAPON_SmokeGrenade",
}

**Comment by GabbarFramework** [comment]
@tom-osborne Do You Have Any Fix For This

**Comment by tom-osborne** [comment]
I can't replicate it on my server. While eating a sandwich, it blocks any action. So cannot press h to search.

**Comment by GabbarFramework** [comment]
i m just using default qb server

**Comment by DevSa1** [comment]
i have the same bug Any solution?

**Comment by tom-osborne** [comment]
I have managed to replicate this now. Looking into it...
