### ISSUE TITLE
[BUG]  Vehicle keys some times not giving keys 

### ISSUE THREAD

**Issue by TheMadkat03** [qbcore-framework/qb-vehiclekeys#152]
**Describe the bug**
Vehicle keys some times not giving keys when you   buy / test drive a vehicle or pull a vehicle out of a garage

**To Reproduce**
There is no definitive way to test this it is a random error that seems to happen every 1 in 25 times

**Expected behavior**
Give people keys when it is suppose to ?

**Screenshots**
[script:qb-vehiclekey] SCRIPT ERROR: @qb-vehiclekeys/server/main.lua:70: table index is nil
[   script:qb-garages] SCRIPT ERROR: @qb-garages/server/main.lua:41: table index is nil

**Comment by tom-osborne** [comment]
Update you script and re-test please.

**Comment by TheMadkat03** [comment]
it is up to date

**Comment by TheMadkat03** [comment]
sorry i missed part of the text that i had coppied

**Comment by tom-osborne** [comment]
Your error doesn't match latest version. 

@qb-vehiclekeys/server/main.lua:66:

![image](https://user-images.githubusercontent.com/96954031/186516739-7e7a2a2d-f69c-45be-a428-f9856f0e907f.png)

**Comment by TheMadkat03** [comment]
it is line 70 in vehicle keys i missed a part when i copied

**Comment by tom-osborne** [comment]
And up to date qb-garages?

**Comment by TheMadkat03** [comment]
we are using a Edit of the Garage done by  JDev but i would assume the not giving keys problem which is more of the issue im worried about would be qb-vehiclekeys because its happening on multiple scripts

**Comment by tom-osborne** [comment]
Well the error is suggesting that qb-vehiclekeys is receiving `nil` for the plate so it's likely to be the script which is Triggering the event.

**Comment by TheMadkat03** [comment]
any idea how to fix  it?

**Comment by tom-osborne** [comment]
> 

Check which event is being triggered in your qb-garages when you take out a vehicle. Post a code snippet here of that section of code if you find it.

**Comment by TheMadkat03** [comment]
I don't think it has anything to do with the garage but with the vehicle keys script because its doing that for the vehicle shop to sometimes you get test cars and buy cars and vehicle keys doesn't give you keys

**Comment by TheMadkat03** [comment]
mabey somthing to do with the new server side vehicle spawning?

**Comment by TheMadkat03** [comment]
Windows

**Comment by vibrance3** [comment]
i got the same error

**Comment by vibrance3** [comment]
did you find a way to fix it ?

**Comment by MaDHouSe79** [comment]
just add this to the client file
```lua
CreateThread(function() --Reload Vehicle Key
    while true do        
        QBCore.Functions.TriggerCallback('qb-vehiclekeys:server:GetVehicleKeys', function(keys)
	    KeysList = keys
	end)
	Wait(3000)
    end
end)
```
it fix the not have keys issue.....

**Comment by Ginjakz** [comment]
Did you add this anywhere specific?
