### ISSUE TITLE
[BUG] Config.LockNPCParkedCars = true - causes player cars to become locked when they get out without locking

### ISSUE THREAD

**Issue by ChickenDipper1** [qbcore-framework/qb-vehiclekeys#156]
**Describe the bug**
When this setting is true, if a player gets out of their car and does not lock it another player cannot get in the car even if the door is open, this is still true if the player that owns the car unlocks it another player will still not be able to get in the drivers seat.

**To Reproduce**
1. Get out of owned car without locking
2. Let player try to get in and drive.
3. It will seem like the door is locked with the animation even if the owner unlocks it.

**Expected behavior**
Car should remain unlocked if the owner or key holder did not lock.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

**Comment by CptNoHand** [comment]
Yes, same.

**Comment by manugo-dev** [comment]
Same here

**Comment by Z3rio** [comment]
I have now tested this, it seems to be a valid issue.
The dev team will be looking over this as soon as possible!

**Comment by CptNoHand** [comment]
Good to hear, hope that get's fixed. this is a bit of a problem atm.

**Comment by CptNoHand** [comment]
Will this get fixed?, this is kinda a big problem on bigger servers

**Comment by tom-osborne** [comment]
> Will this get fixed?, this is kinda a big problem on bigger servers

Yes, I am working on a fix. I hope to get it sorted this week.

**Comment by tom-osborne** [comment]
@CptNoHand @ChickenDipper1 @manugo-dev @Z3rio 

Would appreciate if you could test the linked PR above, thanks.

**Comment by ChickenDipper1** [comment]
Sorry missed the notification for this, happy to test the next version.

**Comment by tom-osborne** [comment]
@CptNoHand @ChickenDipper1 @manugo-dev @Z3rio

New PR above to test please.

**Comment by ChickenDipper1** [comment]
Working as expected

**Comment by SirOMGitsYOU** [comment]
Just tested the PR on my server if you start the engine and lock the vehicle or have someone in the vehicle and it gets locked it then becomes almost impossible to lock the car again

**Comment by ChickenDipper1** [comment]
> Just tested the PR on my server if you start the engine and lock the vehicle or have someone in the vehicle and it gets locked it then becomes almost impossible to lock the car again
Try this:
https://github.com/qbcore-framework/qb-vehiclekeys/pull/163

**Comment by SirOMGitsYOU** [comment]
> > Just tested the PR on my server if you start the engine and lock the vehicle or have someone in the vehicle and it gets locked it then becomes almost impossible to lock the car again
> > Try this:
> > #163

cheers seen this after my message

**Comment by brynnie1** [comment]
Tried this with the push above but now we cant lock the vehicles

**Comment by tom-osborne** [comment]
> Tried this with the push above but now we cant lock the vehicles

@brynnie1 How are you locking the vehicles?
If you are outside the vehicle, make sure you are stood next to it and facing the vehicle.

**Comment by brynnie1** [comment]
> > Tried this with the push above but now we cant lock the vehicles
> 
> @brynnie1 How are you locking the vehicles? If you are outside the vehicle, make sure you are stood next to it and facing the vehicle.

Ye i'm stood infront of it - I have replied to the latest push one which you says fixes a few issues, espeically with people who own vehicles are auto locking when they get out, and others cant get in
