### ISSUE TITLE
[SUGGESTION] Leave engine running

### ISSUE THREAD

**Issue by ChickenDipper1** [qbcore-framework/qb-vehiclekeys#157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
A configuration option that allows you to leave engines running if a player gets out of the car without toggling engine off first, if another player hops in and the engine has been left on they can drive the car without hotwiring and are given keys temporarily.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CptNoHand** [comment]
i'd like that.

**Comment by TheProcrastiDad** [comment]
This would be awesome!

**Comment by ChickenDipper1** [comment]
I have this working on my server.

qb-vehiclekeys/client.lua

Change:
`                      -- Hotwiring while in vehicle, also keeps engine off for vehicles you don't own keys to
            if IsPedInAnyVehicle(ped, false) and not IsHotwiring then
                sleep = 1000
                local vehicle = GetVehiclePedIsIn(ped)
                local plate = QBCore.Functions.GetPlate(vehicle)

                if GetPedInVehicleSeat(vehicle, -1) == PlayerPedId() and not HasKeys(plate) and not isBlacklistedVehicle(vehicle) and not AreKeysJobShared(vehicle) then
                    sleep = 0

                    local vehiclePos = GetOffsetFromEntityInWorldCoords(vehicle, 0.0, 1.0, 0.5)
                    DrawText3D(vehiclePos.x, vehiclePos.y, vehiclePos.z, Lang:t("info.skeys"))
                    SetVehicleEngineOn(vehicle, false, false, true)

                    if IsControlJustPressed(0, 74) then
                        Hotwire(vehicle, plate)
                    end
                end
            end`


to:

`            -- Hotwiring while in vehicle, also keeps engine off for vehicles you don't own keys to
            if IsPedInAnyVehicle(ped, false) and not IsHotwiring then
                sleep = 500
                local vehicle = GetVehiclePedIsIn(ped)
                local plate = QBCore.Functions.GetPlate(vehicle)

                local EngineOn = GetIsVehicleEngineRunning(GetVehiclePedIsIn(PlayerPedId()))
                local vehicle = GetVehiclePedIsIn(ped)
                if EngineOn then
                    SetVehicleEngineOn(vehicle, true, false, true)
                    elseif GetPedInVehicleSeat(vehicle, -1) == PlayerPedId() and not HasKeys(plate) and not isBlacklistedVehicle(vehicle) and not AreKeysJobShared(vehicle) then
                    sleep = 0

                    local vehiclePos = GetOffsetFromEntityInWorldCoords(vehicle, 0.0, 1.0, 0.5)
                    DrawText3D(vehiclePos.x, vehiclePos.y, vehiclePos.z, Lang:t("info.skeys"))
                    SetVehicleEngineOn(vehicle, false, false, true)

                    if IsControlJustPressed(0, 74) then
                        Hotwire(vehicle, plate)
                    end
                end
            end`

This should keep the engine running if the car was left running when another player jumps in.
