### ISSUE TITLE
[Possible BUG] "G" key for engine only keeps restarting engine

### ISSUE THREAD

**Issue by The-MacNasty** [qbcore-framework/qb-vehiclekeys#162]
**Describe the bug**
When in a vehicle and press the G key to shut the engine off while it is already running it then just puts the vehicle in the start process and restarts it. It does not shut it off.

**To Reproduce**
1. Get inside any running vehicle
2. Press the G key to turn engine off.
3. Engine just restarts, does not shut off

**Expected behavior**
To turn engine off

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Went thru and updated today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by tom-osborne** [comment]
@The-MacNasty Are you using the default qb-hud? If so, can you confirm that you have both qb-hud and qb-vehiclekeys up to date? They were both updated very recently with some minor changes to the engine toggle function.

**Comment by The-MacNasty** [comment]
let me make sure with the Hud. I will get back with you. Thank you!

**Comment by The-MacNasty** [comment]
We use a different hud.. but it did have the same engine command as qb-hud. after removing that command, it worked. Thankyou!
