### ISSUE TITLE
[SUGGESTION] Add a config option to disable vehicle jacking

### ISSUE THREAD

**Issue by SPKReality** [qbcore-framework/qb-vehiclekeys#165]
**Is your feature request related to a problem? Please describe.**
It is not related to a issue nor a problem

-----------

**Describe the feature you'd like**
For you to add a config option to either enable car jacking or disable car jacking.

-----------

**Additional context**
No Additional content this is just a little suggestion. Sorry for not going into much detail.

**Comment by tom-osborne** [comment]
Should be covered by #161

**Comment by SPKReality** [comment]
sick mate cheers

**Comment by tom-osborne** [comment]
Added in #161
