### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Xoogle5M** [qbcore-framework/qb-vehiclekeys#167]
**Describe the bug**
The shared vehicle keys for jobs doesn't seem to be working. Tried while on duty and off duty, neither worked.

**To Reproduce**
1. Make sure the correct vehicles are put into the config.lua
2. Make sure both players have the correct job (police)
3. Check if the player that did not grab the vehicle has keys
4. Player 2 ends up not having keys 

**Expected behavior**
Everyone with the same job should have shared keys to the vehicles listed under their job in Config.SharedKeys

**Questions (please complete the following information):**
 - Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] - No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] - No

**Comment by tom-osborne** [comment]
Is this happening with an addon vehicle?
If so, then check this issue, where a potential cause was explained. #164 
This was also fixed in a recent PR, so you can simply update to fix the issue

**Comment by Xoogle5M** [comment]
> Is this happening with an addon vehicle? If so, then check this issue, where a potential cause was explained. #164 This was also fixed in a recent PR, so you can simply update to fix the issue

Yeah, they are addon vehicles. Should they be in shared/vehicles.lua by the way? I haven't put them in there cause I didn't want them available in shops.

**Comment by tom-osborne** [comment]
Yes they should. Also, grab a copy of the latest version of qb-vehiclekeys and you should have the shared jobs fixed.

**Comment by tom-osborne** [comment]
@Xoogle5M Did that fix your issue?
