### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skrimxyz** [qbcore-framework/qb-vehiclekeys#168]
**Describe the bug**
When someone that doesn't have the vehicle keys want's to enter in a car that is not closed, the door's from the specific car is auto closing and the lock/unlock car function is useless because they are autolock.

**To Reproduce**
1. Exit from the car that you have and don't lock it
2. Tell someone to hop in the car
3. You will see the car is locked

**Expected behavior**
When you leave the vehicle and you don't lock the doors, other persons can enter the car but they can't lock the door or start the car

**Screenshots**
-

**Questions (please complete the following information):**
 - When you last updated: -Today
 - Are you using custom resource? which ones? -No
 - Have you renamed `qb-` to something custom? No

**Additional context**
-

**Comment by tom-osborne** [comment]
@skrimxyz was this resolved?

**Comment by skrimxyz** [comment]
> @skrimxyz was this resolved?

yup yup

**Comment by skrimxyz** [comment]
> @skrimxyz was this resolved?

@tom-osborne Hey, I got another issue, after solving my problem that I posted, now the parked cars are unlocked. I know it's from the config but it's weird so if I set the Config.LockNPCParkedCars to true it will auto lock again the cars for players

**Comment by tom-osborne** [comment]
@skrimxyz Yeah I have a fix for this that is being tested. You can also try it out. See here: https://github.com/qbcore-framework/qb-vehiclekeys/pull/163
