### ISSUE TITLE
[BUG] Config.TimeBetweenHotwires - no effect

### ISSUE THREAD

**Issue by ChickenDipper1** [qbcore-framework/qb-vehiclekeys#170]
**Describe the bug**
The TimeBetweenHotwires setting has no effect, you can instantly hotwire (search for keys) after failing.

**To Reproduce**
1. Get in an unowned car by entering it while unlocked or lockpicking the door
2. Press H to search keys / hotwire (same thing)
3. Fail to find keys/hotwire
4. Press H again to search again, no matter what the TimeBetweenHotwires is set to.

**Expected behavior**
TimeBetweenHotwires should apply, so when searching keys/hotwiring you cannot spam this.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today to test this issue
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**
N/A

**Comment by ChickenDipper1** [comment]
Fix:

Find
`if IsControlJustPressed(0, 74) then
                        Hotwire(vehicle, plate)`


Add after
`Wait(Config.TimeBetweenHotwires)`

**Comment by tom-osborne** [comment]
@ChickenDipper1 currently the time between hotwires only applies to successful hotwires. If you fail, you can attempt straight away, but if you succeed then you cannot hotwire again until that time has passed.

**Comment by ChickenDipper1** [comment]
Oh I see, apologies I didn't realise this was the design.

I suppose hotwiring can be kind of limited by adjusting the speed of hotwire, but i'll submit a feature request as I do think this should apply to both unsuccessful and successful hotwires. 
Possibly something along the lines of "you messed up the wires" meaning you cannot try again in that car.

Thanks for the info.

**Comment by tom-osborne** [comment]
We can improve this by changing the config time to Time between successful hotwires. And then add another for time between failed hotwires.

**Comment by ChickenDipper1** [comment]
That would be perfect!
