### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CptCoggs** [qbcore-framework/qb-vehiclekeys#172]
Hi - We seem to have encountered a bug where we get stuck in a vehicle (cannot exit it, cannot move the vehicle, etc) if entering another players vehicle, and sometimes even entering our own vehicles. 

Has anyone else encountered this problem and if so does anyone know how to fix it?

We are on the most recent version and have not renamed qb to anything else.

**Comment by SirOMGitsYOU** [comment]
> Try #163

Using #163 and still having the issues albeit less prevalent

**Comment by tom-osborne** [comment]
Okay, thanks for the feedback.

I might add in some debug prints and ask you to run with those if that's okay. Then maybe we can try to troubleshoot the exact issue you are seeing.

**Comment by SirOMGitsYOU** [comment]
Yeah honestly anything to identify the issue would be great :D

**Comment by tom-osborne** [comment]
Sounds like an NUI is being activated for something? If you have NUI dev tools available, then you can investigate if you know how

**Comment by SirOMGitsYOU** [comment]
> Sounds like an NUI is being activated for something? If you have NUI dev tools available, then you can investigate if you know how

We think we might have figured what could be causing our issue but if anything it adds even more confusion to the situation qb-smallresources not sure if it’s the culprit but occasionally our arms will get locked in place sort of like we’re still stuck in an animation and the only way to fix is by spamming x until the hands go up this then fixes it until it happens again ofc

**Comment by tom-osborne** [comment]
@SirOMGitsYOU Is there any chance that getting stuck in the vehicle might be related to using the harness?

If so, see here for a possible solution: https://github.com/qbcore-framework/qb-smallresources/pull/283

**Comment by buntyverma69** [comment]
> @SirOMGitsYOU @CptCoggs Is there any chance that getting stuck in the vehicle might be related to using the harness?
> 
> If so, see here for a possible solution: [qbcore-framework/qb-smallresources#283](https://github.com/qbcore-framework/qb-smallresources/pull/283)

if they are using harness they are stuck some times you are stuck because off handsup and dpemotes script are trigger same time emote key x .

**Comment by buntyverma69** [comment]
@tom-osborne can you revert back the handsup events?

**Comment by SirOMGitsYOU** [comment]
> @SirOMGitsYOU @CptCoggs Is there any chance that getting stuck in the vehicle might be related to using the harness?
> 
> If so, see here for a possible solution: [qbcore-framework/qb-smallresources#283](https://github.com/qbcore-framework/qb-smallresources/pull/283)

Not using harness' due to that issue. Could be related to handsup clash between dpemotes tho as previously mentioned ^

**Comment by tom-osborne** [comment]
> @tom-osborne can you revert back the handsup events?

Revert what exactly?

**Comment by buntyverma69** [comment]
> > @SirOMGitsYOU @CptCoggs Is there any chance that getting stuck in the vehicle might be related to using the harness?
> > If so, see here for a possible solution: [qbcore-framework/qb-smallresources#283](https://github.com/qbcore-framework/qb-smallresources/pull/283)
> 
> Not using harness' due to that issue. Could be related to handsup clash between dpemotes tho as previously mentioned ^

i fixed it for temporary if i have time to fixed properly then i open pull request

**Comment by buntyverma69** [comment]
> > @tom-osborne can you revert back the handsup events?
> 
> Revert what exactly?

old handsup.lua functions

**Comment by SirOMGitsYOU** [comment]
> > @tom-osborne can you revert back the handsup events?
> 
> Revert what exactly?

To clarify what he’s trying to say, there was an update to handsup.lua which rewrote the script, this rewrite whatever was changed has buggered this causing the issue where you get trapped in your vehicle if you revert to the last update before that then you don’t have any of the issues getting stuck in the car since reverting not had a single issue

**Comment by tom-osborne** [comment]
@SirOMGitsYOU Do you have any steps to be able to replicate getting trapped? I'd like to understand this better.

**Comment by SirOMGitsYOU** [comment]
> @SirOMGitsYOU Do you have any steps to be able to replicate getting trapped? I'd like to understand this better.

Sadly we haven’t been able to replicate the steps or figure out what causes it the only thing I can tell you is that something in the new handsup.LUA definitely is the issue

**Comment by Edvo1901** [comment]
Hi guys, im getting a same issue, I figure out that this is cause by the handsup event in qb-smallresource but I'm not too sure what is the problem

**Comment by SirOMGitsYOU** [comment]
> Hi guys, im getting a same issue, I figure out that this is cause by the handsup event in qb-smallresource but I'm not too sure what is the problem

The only fix I was able to do was to change the keybind for handsup, I posted a modified handsup.LUA in the discord somewhere that will globally change the keybind without having to manually change it

**Comment by Edvo1901** [comment]
> > Hi guys, im getting a same issue, I figure out that this is cause by the handsup event in qb-smallresource but I'm not too sure what is the problem
> 
> The only fix I was able to do was to change the keybind for handsup, I posted a modified handsup.LUA in the discord somewhere that will globally change the keybind without having to manually change it

It would be nice if you can give me a link to that fix. Thanks

**Comment by SirOMGitsYOU** [comment]
https://discord.com/channels/831626422232678481/1026308695270895646/1038586970827407421
