### ISSUE TITLE
[BUG] LockState inconsistent

### ISSUE THREAD

**Issue by Sharkiiie** [qbcore-framework/qb-vehiclekeys#178]
**Describe the bug**
The LockState is inconsistent when passengers attempt to enter or exit a vehicle.

- If a vehicle is locked, and a player with keys toggles the locks, but another player attempts to enter the vehicle prior to the key holder, the vehicle sometimes becomes locked again. 
To avoid this, the owner of the vehicle must unlock and sit in the driver seat first.

- If a vehicle is unlocked, and a passenger sits in the vehicle, then exits the vehicle, the vehicle will become locked again with no toggle input.

**To Reproduce**
1. Unlock a cars doors
2. Have another player attempt to enter passenger seat
3. Attempt to enter vehicle
4. Vehicle has re-locked for all players (sometimes)

OR
1. Unlock vehicle
2. Enter vehicle
3. Have passenger enter vehicle
4. Exit vehicle 
5. Have passenger exit vehicle 
6. Either owner or passenger attempt to enter vehicle
7. Vehicle has re-locked for all players (always, as far as I can tell)

**Expected behavior**
A vehicles door lock state should be toggled between locked or unlocked for all players, and should remain in the chosen state regardless of which player enters or exits said vehicle.

**Screenshots**
Can be provided later if needed.

**Questions (please complete the following information):**
 - When you last updated: Today, latest vehiclekeys
 - Are you using custom resource? Yes, none affecting vehiclekeys
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

**Comment by tom-osborne** [comment]
Great issue report, thank you. This is a known issue and is addressed in #163. Please test with that and see if it resolves the issue for you.
