### ISSUE TITLE
[BUG] SetVehicleAlarm not working

### ISSUE THREAD

**Issue by LukeeeChan** [qbcore-framework/qb-vehiclekeys#179]
No matter what I do, the vehicle's alarm will not go off when I am hotwiring.

**Comment by tom-osborne** [comment]
Works every time for me, are you using standard qb-vehiclekeys? Is it up to date?

**Comment by LukeeeChan** [comment]
It has not worked for me, and it is up to date. I have modified it a little, but it should not matter, as the code for this issue contains two lines, right?

**Comment by tom-osborne** [comment]
Do you have the problem on all cars? Could it jkust be isolated to some addon vehicles perhaps?

**Comment by LukeeeChan** [comment]
Yes, unfortunately I've had it with all the vehicles.

**Comment by FrogCF** [comment]
Hello, 
Thank you for your question this is my suggestion. Please try a clean copy of vehicle keys without modding anything in the file I've tested this version on a test bed with no concerns or problems or any LUA.errors showing.

Please can you provide us with a little more information? 

Or join QB-CORE Discord: https://discord.com/invite/qbcore

**Comment by ahmed608** [comment]
I will add it soon, inshaa allah thank you for report
