### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Belorico** [qbcore-framework/qb-vehiclekeys#18]
Make the auto theft more realistic. If you are pulling someone from vehicle with engine is running there should be no need to Hotwire or lockpick the ignition. If the vehicle is parked then you should need to lockpick the door lock and Hotwire the ignition.

**Comment by BerkieBb** [comment]
Thank you for the suggestion, I am currently working on making this resource better so I will take this into the changes

**Comment by Belorico** [comment]
Thank you for the answer... And for your efforts... Im trying do develop my skills fast and hope I can help you guys soon.
