### ISSUE TITLE
Lock Pick Parked Cars

### ISSUE THREAD

**Issue by RoyalRaid** [qbcore-framework/qb-vehiclekeys#180]
**Describe the bug**
After successfully lock picking a parked car with either advanced lock with or standard, the car remains locked and im unable to open.

**Steps to reproduce the behavior:**

1) Walk up to randomly spawned park car
2) Successfully lockpick car
3) Try to open vehicle

**Screenshots**
N/A

**Questions (please complete the following information):**
When you last updated: Today
Are you using custom resource? which ones? No
Have you renamed qb- to something custom? No

**Additional context**
N/A

**Comment by tom-osborne** [comment]
Works fine for me on a fresh build. Have you changed anything in the config?
