### ISSUE TITLE
[BUG] Being able to open NPC Parked car door and sit in it when having config set to true (After fix #156)

### ISSUE THREAD

**Issue by NikoClapz** [qbcore-framework/qb-vehiclekeys#181]
**Describe the bug**
Being able to open door of NPC Parked cars when I have the config set to true.

**To Reproduce**
1. Config.LockNPCParkedCars = true (NPC Parked Cars are not locked) after fixes #156 
2. Click F on NPC Car Door and can get in no problem
3. No errors
**Expected behavior**
To not be able to break window/open the NPC Door in general
**Screenshots**
https://cdn.discordapp.com/attachments/1031760465384194088/1031857642995462184/unknown.png

**Questions (please complete the following information):**
 - When you last updated: Updated last qb-vehiclekeys and updated client/server with #156 
 - No custom
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by tom-osborne** [comment]
Check your script hasn't got any errors. Sounds like something has caused the script to fail and you therefore just have default gta behaviour,  which let's you break into cars.

**Comment by NikoClapz** [comment]
> Check your script hasn't got any errors. Sounds like something has caused the script to fail and you therefore just have default gta behaviour, which let's you break into cars.

Thanks so much for the quick reply. No errors in console

**Comment by tom-osborne** [comment]
@NikoClapz did you get this resolved?
