### ISSUE TITLE
[BUG] Vehicle won't stay off

### ISSUE THREAD

**Issue by Blaez** [qbcore-framework/qb-vehiclekeys#183]
**Describe the bug**
The vehicle will not stay off when manually turning the car off

**To Reproduce**
1. Get in the car and turn off the car with "G" or custom key bind
2. The Car should stay off until turned back on
4. See the error

**Expected behavior**
The car should stay off until the keybind is pressed again

**Questions (please complete the following information):**
 - When you last updated: 10/29/22
 - Are you using custom resource? which ones? {?}
 - Have you renamed `qb-` to something custom? [No]

**Additional context**

**Comment by tom-osborne** [comment]
It is likely that you have a conflicting keybind. This happens a lot for people who use ps-hud as the G key for engine toggle is also registered there as well as qb-vehiclekeys. You can disable it in one of those resources and it should work as intended.

This was also a problem with qb-hud up until 2 months ago. So if you are running with old code, update qb-hud and qb-vehiclekeys.

**Comment by Blaez** [comment]
Thank you, I removed the engine toggle code from qb-hud and it works as expected.
