### ISSUE TITLE
Doorlocks not working, stuck in animation[BUG]

### ISSUE THREAD

**Issue by onstormchaser** [qbcore-framework/qb-vehiclekeys#185]
**Describe the bug**
When pressing L to lock the doors you hear the sound and the key fob animation loops continuously. No notification for locked or unlocked pops up and the doors do not lock or unlock. No f8 errors or server side errors.

**To Reproduce**
1. Just pressing L to unlock the car.

**Expected behavior**
The door locks should lock and unlock and the animation should not be continuous. Notifications of doors locked or unlocked should also be present.

**Screenshots**.

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? many 
 - Have you renamed `qb-` to something custom? no

**Additional context**
Was working fine until i updated a bunch of qb scripts

**Comment by TheGoatRico** [comment]
Same issue happening to me.

**Comment by tom-osborne** [comment]
Key fob?

Are you using the keyfob from https://github.com/qbcore-framework/qb-vehiclekeys/pull/177 ?

**Comment by onstormchaser** [comment]
> 

No, I mean the animation that our character does when locking and unlocking.

**Comment by ahmed608** [comment]
This error is already fixed in my pr
