### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PandaKeny** [qbcore-framework/qb-vehiclekeys#187]
Get on npc vehicle without lockpick can still run

**Comment by tom-osborne** [comment]
Quality issue. Honestly impressed...

**Comment by ahmed608** [comment]
I will add it soon, inshaa allah thank you for report

**Comment by PandaKeny** [comment]
What do you mean I'm doing something wrong?

**Comment by tom-osborne** [comment]
> What do you mean I'm doing something wrong?

> > Get on npc vehicle without lockpick can still run

**Comment by Donnyjohn1** [comment]
i have same issue, when stealing a parked car dont have to lock pick, does the regular gta animation where it breaks the glass does a 2 second hotwire and you drive off, its as if the whole systems not even working lol

**Comment by PandaKeny** [comment]
> i have same issue, when stealing a parked car dont have to lock pick, does the regular gta animation where it breaks the glass does a 2 second hotwire and you drive off, its as if the whole systems not even working lol

yes i mean like that

**Comment by tom-osborne** [comment]
> i have same issue, when stealing a parked car dont have to lock pick, does the regular gta animation where it breaks the glass does a 2 second hotwire and you drive off, its as if the whole systems not even working lol

Update your core. Make sure you have the entering vehicle events in there as that's what it relies on now.

In particular, make sure you have these files up to date: 
https://github.com/qbcore-framework/qb-core/blob/main/client/events.lua
https://github.com/qbcore-framework/qb-core/blob/main/server/events.lua

**Comment by ChickenDipper1** [comment]
> > i have same issue, when stealing a parked car dont have to lock pick, does the regular gta animation where it breaks the glass does a 2 second hotwire and you drive off, its as if the whole systems not even working lol
> 
> Update your core. Make sure you have the entering vehicle events in there as that's what it relies on now.
> 
> In particular, make sure you have these files up to date: https://github.com/qbcore-framework/qb-core/blob/main/client/events.lua https://github.com/qbcore-framework/qb-core/blob/main/server/events.lua

I had this issue where you can start the engine on any car without keys and without hotwire.
I update my core as you mentioned here but the issue is still the same.

Thanks.
