### ISSUE TITLE
[BUG] latest commit to qb-core has broken the qb-vehiclekeys script.

### ISSUE THREAD

**Issue by tom-osborne** [qbcore-framework/qb-vehiclekeys#188]
**Describe the bug**
Since [#883](https://github.com/qbcore-framework/qb-core/pull/883) was merged qb-vehiclekeys no longer works as the vehicle events were removed. 

Please check your merges guys and make sure you are working to the latest version. @Z3rio its likely that it worked for you because you tested on an old server build prior to [#883](https://github.com/qbcore-framework/qb-core/pull/883). Always test on a fresh build, or make sure you pull the latest code.

[#883](https://github.com/qbcore-framework/qb-core/pull/883) this should not have been merged

**To Reproduce**
1. Build fresh server
2. Enter any vehicle you want because it does not check for the entering vehicle event.

**Comment by Z3rio** [comment]
Fixed in newest qb-core PR
