### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by siebe8000o** [qbcore-framework/qb-vehiclekeys#191]
**Describe the bug**
I got some errors when i get in the vehicle. I updated the core I updated the vehiclekeys and got those errors. I can get in every vehicle and drive off just like that. What I have changed is the core name nothing more

**Screenshots**
![image_2022-12-24_140128948](https://user-images.githubusercontent.com/104435266/209437417-6c04a520-9bb1-4e10-a9d4-1e962e9a242e.png)

![image_2022-12-24_140109750](https://user-images.githubusercontent.com/104435266/209437410-92e8fd05-a855-4ff6-b30b-03f6921d7688.png)

**To Reproduce**
1. Go to a car and get in and you have the keys, or spawn the car and you have them to
2. Click on 'L' and he will give the error that their is not an target car
3. See error

**Expected behavior**
The cars not to start and that their are no errors anymore

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] just an hour ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]  yes, London studios matrix, m-insurance, m-carrebuild, m-tunerjob, GKSphone
 - Have you renamed `qb-` to something custom? yes, Only the core is renamed nothing more

**Comment by tom-osborne** [comment]
https://github.com/qbcore-framework/qb-vehiclekeys/blob/main/client/main.lua#L370
Export is there. Re-install with latest version of qb-vehiclekeys
