### ISSUE TITLE
[BUG] Keys not working

### ISSUE THREAD

**Issue by Leveecius88** [qbcore-framework/qb-vehiclekeys#193]
Brand new install, no configs edited or anything.  All spawned or addon vehicles within server keep giving me the error I don't have keys to this vehicle.  It's not giving me the keys either.  Readme says squat and no instructions either.  How can I get the keys to my addon vehicles so I can not keep getting locked out of them and having to re-spawn every time?

**Comment by estrela91pt** [comment]
I also have the same problem

**Comment by Leveecius88** [comment]
> I also have the same problem

I found that vehicles spawned in vMenu do this, however, if you spawn them with the admin menu section, it works fine.  At least for me

**Comment by LeoMercy** [comment]
> > I also have the same problem
> 
> I found that vehicles spawned in vMenu do this, however, if you spawn them with the admin menu section, it works fine. At least for me

Hey the problem is that when u spawn the car you dont own it so thats why u dont have keys. you can own it by command /admincar but for that u have to add that vehicle in qn-core/shared/vehicles.lua too

**Comment by TankinTom** [comment]
The issue this causes, is that if you're using a vehicle spawner, for a job, you wont get keys. That seems like a pretty big issue.

**Comment by owlel** [comment]
did you figure out a solution? have this too. when purchasing a vehicle me and everyone else in game dont get notified that we received keys. the keys are just not known.. it locks us out and tells me i dont have keys to this vehicle. cant store in garage either.

**Comment by TankinTom** [comment]
> 

So for this, make sure in your job, that the fuel system you're using matches. We had recently change to CDN-Fuel, and I didn't change the export to the ambulance job, and as soon as I made that change, I restarted the script, spawned the vehicle, and got the keys.

**Comment by owlel** [comment]
> > 
> 
> So for this, make sure in your job, that the fuel system you're using matches. We had recently change to CDN-Fuel, and I didn't change the export to the ambulance job, and as soon as I made that change, I restarted the script, spawned the vehicle, and got the keys.

ah.. i was wondering if it was a fuel issue because right now im using ps-fuel. so i would have to switch to cdn?

**Comment by TankinTom** [comment]
> > > 
> > 
> > 
> > So for this, make sure in your job, that the fuel system you're using matches. We had recently change to CDN-Fuel, and I didn't change the export to the ambulance job, and as soon as I made that change, I restarted the script, spawned the vehicle, and got the keys.
> 
> ah.. i was wondering if it was a fuel issue because right now im using ps-fuel. so i would have to switch to cdn? or remove ps-fuel?

Well No, you'd have to make sure that your vehicle spawns are using whatever fuel system your server is using. For some reason, the ambulance export for vehicles was set to LegacyFuel still, as soon as I changed it to match our actual fuel system, I got the keys.

**Comment by owlel** [comment]
> > > > 
> > > 
> > > 
> > > So for this, make sure in your job, that the fuel system you're using matches. We had recently change to CDN-Fuel, and I didn't change the export to the ambulance job, and as soon as I made that change, I restarted the script, spawned the vehicle, and got the keys.
> > 
> > 
> > ah.. i was wondering if it was a fuel issue because right now im using ps-fuel. so i would have to switch to cdn? or remove ps-fuel?
> 
> Well No, you'd have to make sure that your vehicle spawns are using whatever fuel system your server is using. For some reason, the ambulance export for vehicles was set to LegacyFuel still, as soon as I changed it to match our actual fuel system, I got the keys.

got it! i replaced the fuels to all be the same one, but now no vehicles will spawn in nor i cant buy any.. im new at this and still learning but atleast now i know they're both connected lol

**Comment by Z3rio** [comment]
Not a real issue. Just incorrect usage
