### ISSUE TITLE
[BUG] Car Jacking is not working Newest qb-core framework install.

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-vehiclekeys#194]
**Describe the bug**
With a new updated version of qbcore including vehicle keys I was testing the car jacking and when I point a pistol at a NPC in a car nothing happens.  They look at me briefly then drive away. I checked both the server console and client console and no errors. Anyone know how to fix this? 

I already have all the updates because it is a fresh server install.

**Comment by pifaro** [comment]
Same issue here. Updated qb-vehicleys and:
Carjacking not working when pointing a gun at driver NPC; NPC driving a car is not locked; Robbing parked cars automatically hotwires it and does not have the option to search for keys

**Comment by pifaro** [comment]
Fixed it by updating qb-core

**Comment by twigmasters** [comment]
I have the most current version of qb-core and vehicle keys and still same issue i posted above.

**Comment by KamiDaStreet** [comment]
I have the same problem

**Comment by Cupidojex** [comment]
i have the same!! if this fix,  i need the function  to work!

**Comment by spookstuh** [comment]
find fix for this im getting the same problem?

**Comment by KingRyuShin** [comment]
Keeping this up, the fix is the put the robloop in a thread and not un a function being called one time

**Comment by L1GHTNINGx** [comment]
any fix for this?

**Comment by singh-manavv** [comment]
Just tested this , it works perfectly fine. Couldn't reproduce the issue so i will be closing this thread.
