### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zerlot120** [qbcore-framework/qb-vehiclekeys#198]
Greeting,

I'm interested, when the player gets out of the car, you can still turn the car on and off by pressing the g button.

is it g for example when you do a job like qb-hotdogjob when you take a stand on the g button if there is a car nearby it freezes the player and later I can't move at all with the character in the game

I'm interested in where I can remove that control on the g button from the vehicle key or replace it with an option when it's in the vehicle so that only that button can be used

**Comment by sp1d3r1987** [comment]
Zerlott120, if you goto the config and change the Config.UseKeyfob = false to Config.UseKeyfob = true 
this disables the keyfob use and just uses the old lock/unlock method

**Comment by ChristianBDev** [comment]
@zerlot120 #201 fixes this
