### ISSUE TITLE
[SUGGESTION] easy way to unlock/lock car

### ISSUE THREAD

**Issue by AIADHD** [qbcore-framework/qb-vehiclekeys#202]
easy way to unlock/lock car
is hard to unlock while run from the cop

**Comment by ChristianBDev** [comment]
@AIADHD Can you elaborate more please?

**Comment by tom-osborne** [comment]
This is not a suggestion

**Comment by Suranos** [comment]
I think he is referring to add an option in Config to increase lock distance, Currently you have to be right on top of the car to unlock/lock it, and even sometimes that isn't close enough. 

So something like: Config.LockDistance = 3.0,

**Comment by GitMocha** [comment]
Seems a decent enough distance. Not sure why you'd want it any further. Could just be abused.. It also DOESN'T require you to be 'right on top' of the car..
![Screenshot_6](https://user-images.githubusercontent.com/97256967/222562411-a1cfdd3f-f454-43b7-9fe7-2dcbd4516013.png)

![Screenshot_5](https://user-images.githubusercontent.com/97256967/222562395-213b745b-f0eb-452e-b4bb-b7326e613fa2.png)

**Comment by Deeros** [comment]
> 
How do you unlock your vehicle with just one key? Me when I do L, it shows me a vehicle key

**Comment by Deeros** [comment]
> > 
> 
> Turns out I had a bug in mine, re-uploaded to latest version and now I no longer have to hump my door to unlock the car.

How do you unlock your vehicle with just one key? Me when I do L, it shows me a vehicle key
