### ISSUE TITLE
[BUG] Lockpick Does Not Grant Vehicle Keys

### ISSUE THREAD

**Issue by CloakedManz** [qbcore-framework/qb-vehiclekeys#205]
**Describe the bug**
Hey! When lockpicking a LOCKED NPC car, upon completion of the lockpick the vehicle keys are not given and the vehicle CANNOT be opened.

**To Reproduce**
1. Go to a LOCKED NPC Car
2. Complete the lockpick minigame
3. Try to open the door
4. Door does not open.

**Expected behavior**
Keys are given for the vehicle and the door is unlocked.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 2/17/23
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

**Comment by GitMocha** [comment]
Seems to work fine, unless you've altered something..? U lockpick the vehicle, get in, press [H] to search for keys.
![Screenshot_1](https://user-images.githubusercontent.com/97256967/222561270-445e2f16-95a0-4e45-8cde-17d5c41c6ed5.png)
![Screenshot_2](https://user-images.githubusercontent.com/97256967/222561280-f83225f2-347b-4cb3-9d7b-22d8c634d513.png)
![Screenshot_3](https://user-images.githubusercontent.com/97256967/222561287-73da3b39-917d-4958-b507-1b3fa757cfed.png)

**Comment by itzzjd123** [comment]
Hi I am having the same problem and I haven't touched the file at all. It was working fine just the other night and now it doesnt even show up completed once I do it correctly. And even if it breaks it doesn't remove it from the inventory.... any help at all??

> Seems to work fine, unless you've altered something..? U lockpick the vehicle, get in, press [H] to search for keys. ![Screenshot_1](https://user-images.githubusercontent.com/97256967/222561270-445e2f16-95a0-4e45-8cde-17d5c41c6ed5.png) ![Screenshot_2](https://user-images.githubusercontent.com/97256967/222561280-f83225f2-347b-4cb3-9d7b-22d8c634d513.png) ![Screenshot_3](https://user-images.githubusercontent.com/97256967/222561287-73da3b39-917d-4958-b507-1b3fa757cfed.png)
