### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by djsteffantnt** [qbcore-framework/qb-vehiclekeys#207]
**Describe the bug**
Upon server restart or player leaving or rejoining when players retrieve cars parked in the garages, qb-garage or impound, if the player then exits the vehicle and attempts to either lock it or re-enter it they get the error message {you don't own the keys to this vehicle)
**To Reproduce**
1. Park vehicle in any garage or have it impounded.
2. Go to garage or impound
3. Drive away
4. Stop and exit the vehicle
5. Try to lock it or re-enter
6. Message pops up you don't own the keys to this vehicle

**Expected behavior**
The vehicle should operate as owned.

**Questions (please complete the following information):**
 - When you last updated: [2/4/2023] New server
 - Are you using custom resource? which ones? [jim-mechanic]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
I saw a previous report suggesting a number plate script so I removed [jim-plates] however these vehicles do not have custom plates and the error still occurs after removal of said script.

**Comment by djsteffantnt** [comment]
Garbage trucks also do the same thing could it be database related?

**Comment by eygi** [comment]
have you ever found a solution to this bug?
