### ISSUE TITLE
vehicle lights  dont turn on after you lock/unlock vehicle 

### ISSUE THREAD

**Issue by switc7** [qbcore-framework/qb-vehiclekeys#21]

**Comment by ihyajb** [comment]
Thats not in the code so its not an issue, if youd like to see if added into the script please puy [SUGGESTION] in your title so we can add it to the right category. Thank you

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-vehiclekeys/commit/bbccf252f4e5af778c16f265afb05eee9612036d
