### ISSUE TITLE
GetClosestVehicle function not working

### ISSUE THREAD

**Issue by t-weij** [qbcore-framework/qb-vehiclekeys#22]
function LockVehicle() isn't working because 
local veh = QBCore.Functions.GetClosestVehicle()
doesn't seem to work.

If anyone has any idea how to fix this, please let me know.
Thanks in advance

**Comment by Terry-Ligma** [comment]
@t-weij Are you getting any server or client errors in your consoles?

**Comment by t-weij** [comment]
For some reason it doesn't read QBCore Functions ...
Things like GetClosestVehicle don't return anything.
Because we have a nil on GetClosestVehicle, LockVehicle() doesn't do anything, giving us two errors in console, saying ClosestVehicle = nil

**Comment by t-weij** [comment]
@Terry-Ligma  For some reason it doesn't read QBCore Functions ...
Things like GetClosestVehicle don't return anything.
Because we have a nil on GetClosestVehicle, LockVehicle() doesn't do anything, giving us two errors in console, saying ClosestVehicle = nil

**Comment by GhzGarage** [comment]
I imagine maybe your core is not up to date which does not include the imports.lua ??
