### ISSUE TITLE
You don't have keys to this vehicle

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [qbcore-framework/qb-vehiclekeys#228]
**Describe the bug**
So this addon seems to be working fine, exept when used in combination with ik-jobgarage?

**To Reproduce**
1. Open the police job garage (car has been added and is also in shared)
2. Take the custom police car
3. Try to lock/unlock the car
![image](https://github.com/qbcore-framework/qb-vehiclekeys/assets/97805195/ee07a4b1-e8a3-4663-9c6d-f25d5bcb6abe)

**Expected behavior**
When the car is being spawned by using the command **/car carname** everything is fine, but when you "buy" the car from the police garage, you don't get the keys

**Screenshots**
Below is when spawned using **/car carname**

![image](https://github.com/qbcore-framework/qb-vehiclekeys/assets/97805195/6b65533a-6985-4d39-b606-ceed8ba16cd6)

**Questions (please complete the following information):**
 - When you last updated: fresh install a few days ago
 - Are you using custom resource? which ones? ik-jobgarage
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by AnishBplayz** [comment]
You gotta set that in your script from which you buy the police car

**Comment by PCL-CrisKolkman** [comment]
> You gotta set that in your script from which you buy the police car

And exactly "what" should I set in the script (qb-policejob)?

**Comment by AnishBplayz** [comment]
You gotta trigger the givekeys event when you spawn the car

**Comment by PCL-CrisKolkman** [comment]
> You gotta trigger the givekeys event when you spawn the car

But where (and how) to trigger this?
The custom car is spawned from the police garage.
Spawning the car with the command **/car custom_car** gives me the keys to the vehicle but not when spawned from police garage.

**Comment by stevenscotty22** [comment]
im having the same issue
