### ISSUE TITLE
Lockpicking cars removed

### ISSUE THREAD

**Issue by bosskitz** [qbcore-framework/qb-vehiclekeys#23]
After the update 4 hours ago, local cars don't need lockpicking to use. It all became free to use.

**Comment by ihyajb** [comment]
Could not reproduce the issue. I suggest making sure all your scripts are updated.

**Comment by GhzGarage** [comment]
Could not replicate either

**Comment by bosskitz** [comment]
I have made a video of it from start to finish.
1.) Tested qb-vehiclekeys currently installed. -- I cannot steal cars as it needs lockpick.
2.) installed the latest then restarted resources. I can freely use cars
3.) restarted the server and I get the same result.

Video: https://www.youtube.com/watch?v=zWvwG3Hxl0I (HD version may still be processing)

**Comment by ihyajb** [comment]
have you tried updating the script?

**Comment by bosskitz** [comment]
> have you tried updating the script?

Yeah. On the video, I have downloaded the most recent script and installed it.

**Comment by Rhydium** [comment]
Same issue
