### ISSUE TITLE
[BUG] LOCKPICK NOT WORKING

### ISSUE THREAD

**Issue by itzzjd123** [qbcore-framework/qb-vehiclekeys#231]
I am having an issue with lockpicking parked cars. When I go up to the car and lockpick it successfully it doesn’t prompt me that the vehicle has been unlocked or anything and when I try to open the door it’s still locked and when I check my inventory the same amount of lockpicks are still in there even if I break one. I also don’t get any types of error codes in my in game server log nor my regular server log either. I literally haven’t touched the qb-vehiclekeys folder to mess with the lockpicks or anything. Anyone know how to fix this issue?? Please let me know thanks.

**Comment by itzzjd123** [comment]
LINK TO VIDEO LOCKPICK ISSUE [](url) https://forum.cfx.re/t/video-of-lockpick-problem/5150787

**Comment by amirhosin0554** [comment]
yes i have this problem like you

**Comment by poolshark120502** [comment]
how did you fix this issue?

**Comment by amirhosin0554** [comment]
[html.zip](https://github.com/qbcore-framework/qb-vehiclekeys/files/13865575/html.zip)

**Comment by amirhosin0554** [comment]
un zip this file and replaye on /qb-lockpick/html

**Comment by amirhosin0554** [comment]
> how did you fix this issue?

Download html file
