### ISSUE TITLE
[BUG] Vehicle Keys

### ISSUE THREAD

**Issue by mfel2k** [qbcore-framework/qb-vehiclekeys#233]
Every Job I do, including the ones included with the qbcore script, fail to give keys to vehicles when you do a job that gives a vehicle. I am not sure what is causing it and would blame it on the script, but i have 2 addon job scripts, as well as the regular qbcore one that makes you search for keys when you get into the work vehicle.

**Comment by GitMocha** [comment]
Which QB Scripts are not giving you keys when spawning a vehicle? this is usually caused by the script not getting the plate of the vehicle properly when triggering this event "TriggerEvent("vehiclekeys:client:SetOwner".

**Comment by mfel2k** [comment]
To be honest even the qb core jobs from city hall have this issue. Qs drugs,  buty jobs. Also

**Comment by GhzGarage** [comment]
We've tested this with the different jobs and haven't been able to reproduce not receiving keys

**Comment by KingRyuShin** [comment]
same, i had to change the event to use the server one for acquirevehiclekeys

**Comment by mfel2k** [comment]
What did you do to make it work king??

**Comment by mfel2k** [comment]
And instead the of calling it invalid I can let you log into my server and see what happens. I ain't trying to cause issues for u just legitimately want to solve the issue

**Comment by KingRyuShin** [comment]
Just use the AcquireVehicleKeys from server side instead of the SetOwner on client side

**Comment by TreP-coder** [comment]
exports my brother... set it client side of the script.. if escrowed let the person who made it know
