### ISSUE TITLE
[BUG] TxAdmin owners cannot put on seatbelts by pressing 'b'

### ISSUE THREAD

**Issue by daf4ever** [qbcore-framework/qb-vehiclekeys#236]
**Describe the bug**
TxAdmin owners cannot put on seatbelts

**To Reproduce**
- Tried 2 different artifacts including the most recent one. I get in the car, I press 'b' for seatbelt. I hear the clicking noise. Seatbelt sign is still off.
- When I type "/toggleseatbelt" it works
- Issue only appears on owners that can open the txadmin menu
- tried different Permissions: GOD or Admin - both the same, you cannot put on seatbelts 

**Expected behavior**
- Since this issue was posted before from someone else with the same issue and the thread got closed without getting looked at, I hope that this time someone takes time and looks at it since multiple people have the issue 

**Screenshots**
none

**Questions (please complete the following information):**
- Updated Saturday  30th Oktober with a new artifact but problem stayed on different artifact
 - Have you renamed `qb-` to something custom? ---> no

**Comment by KingRyuShin** [comment]
seatbelt is from qb-smallresources and not vehiclekeys

**Comment by daf4ever** [comment]
Thank you KingRyuShin I opened up a ticket there

(https://github.com/qbcore-framework/qb-smallresources/issues/413)
