### ISSUE TITLE
qs-dispatch working with qb-vehiclekeys

### ISSUE THREAD

**Issue by S3V3N17** [qbcore-framework/qb-vehiclekeys#244]
**Is your feature request related to a problem? Please describe.**
not a problem/just unsure how to add a certain export/triggerevent

**Describe the feature you'd like**
im trying to find where exactly i can add an export or trigger event for qs-dispatch to be used in qb-vehiclekeys

**Describe alternatives you've considered**
No alternatives. Just using script as is

**Additional context**
N/A

**Comment by kaynegraham** [comment]
What do you want to use qs-dispatch for?

**Comment by S3V3N17** [comment]
qb-vehiclekeys has the function to alert the police when someone is stealing/lockpicking a vehicle. Our city utilizes qs-dispatch. So i was wondering if there is a way that i can change the triggerevent to read our qs-dispatch system if that makes sense : /

**Comment by GhzGarage** [comment]
Please ask them wherever they offer support
