### ISSUE TITLE
[BUG] Reloading manifest while playing

### ISSUE THREAD

**Issue by Madbull16** [qbcore-framework/qb-vehiclekeys#246]
**Describe the bug**
Players have the problem that sometimes the lock / unlock doesn't work at the first "succes" message.
I noticed that the content manifest sometimes reloads even when playing and triggers the togglelock event.

MainThrd/ OnConnectionProgress: Downloading content manifest...
MainThrd/ OnConnectionProgress: Downloading content manifest (13.07 kB)
UV loop: httpClient/ Required resources: qb-vehiclekeys 
MainThrd/ OnConnectionProgress: Loading content manifest...
MainThrd/ OnConnectionProgress: Downloading qb-vehiclekeys (0 of 1 - 0.00/0.25 MiB)
MainThrd/ OnConnectionProgress: Downloading qb-vehiclekeys (0 of 1 - 0.20/0.25 MiB)
    6676/ ResourceCache::AddEntry: Saved cache:v1:8820a94f40cc42573eea50153260e18c9621e15d to the index cache.
MainThrd/ Creating script environments for qb-vehiclekeys
MainThrd/ OnConnectionProgress: Mounted qb-vehiclekeys (1 of 1)
MainThrd/ Debug: client toggle vehicle door

**To Reproduce**
I was not able to reproduce it on purpose, just made some debug prints and searched the logs.

**Expected behavior**
even if there is some reload (I dont know why) there should not be a toggledoorlock trigger without player using it.

**Comment by TKDubsta1101** [comment]
Hey, we need steps to reproduce this issue in order to assist.

**Comment by Madbull16** [comment]
I looked forward that maybe you could tell me how to reproduce this issue as this "UV Loop" and "redownloading while active playing" does not happen in any other scripts.
