### ISSUE TITLE
[BUG] Not recieving keys for some police vehicles added to the list.

### ISSUE THREAD

**Issue by OldMateFitzy** [qbcore-framework/qb-vehiclekeys#247]
**Describe the bug**
I have been adding many vehicles to the vehicle keys config, But seems that for some reason, some of the cars will just not work. I have completed the steps the correct way on where to add the vehicle ect, But for some reason some Add-on cars will just not work and will not give job "police" the keys on spawn.

Please help this is driving me insane.

My steps include:
-Add vehicle to server
-Add vehicle to qb-core/shared/vehicles.
-Add vehicle to police job.
-Add vehicle to qb-vehiclekeys.

What i dont understand is how can one addon car work, but sometimes one just wont work. I complete the same steps every time and ensure all my spelling is correct.

NOTE: No errors in console.

**Comment by CB1756** [comment]
We are having the same issue as well. Updated my SAST Vehicle pack. Removed all old working vehicles and then readded the ones I updated and now none of those cars are working with the keys at all.

**Comment by OldMateFitzy** [comment]
I couldn’t figure this out so I just moved on from it. I added os-policegarage script for my police vehicles which by passes qb-vehiclekeys as it spawns you in the vehicle and gives you keys on spawn. 100% better :)

**Comment by OldMateFitzy** [comment]
No fix was found for this issue. Os-policegarage was used as an alternative police garage system which worked.
