### ISSUE TITLE
get key

### ISSUE THREAD

**Issue by YouNgWINZy** [qbcore-framework/qb-vehiclekeys#258]
Why does it say I don’t have the key to this vehicle after purchasing the vehicle? How do I get the key?

**Comment by woerki** [comment]
Which vehicle shop do you use?

**Comment by YouNgWINZy** [comment]
> 您使用哪家汽车修理店？

jim

**Comment by YouNgWINZy** [comment]
> 您使用哪家汽车修理店？

qb
