### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Belorico** [qbcore-framework/qb-vehiclekeys#31]
- All spawned/parked cars with closed doors; 
- Cars driven by peds with doors open;
- Cars driven by players open or closed depending on player action;
- Cars dont automatically close when you leave them;
- Stolen cars dont need to be lockpicked by other players to get in;

thank you for your work

**Comment by am3nd01m** [comment]
I would like to see this too.
Thanks guys

**Comment by GhzGarage** [comment]
Should be fixed
