### ISSUE TITLE
Lock/Unlock sound bug

### ISSUE THREAD

**Issue by am3nd01m** [qbcore-framework/qb-vehiclekeys#32]
Hello, when you lock or unlock a car, other players throughout the server can hear the sound effect.
 Using onesync.

**Comment by Wick89** [comment]
you need to get new updated https://github.com/plunkettscott/interact-sound/releases

**Comment by am3nd01m** [comment]
Thank you

**Comment by am3nd01m** [comment]
> 
> 
> you need to get new updated https://github.com/plunkettscott/interact-sound/releases

I updated it and now I can't hear any sounds on my server like locking the car or using the seatbelt.

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/interact-sound

**Comment by am3nd01m** [comment]
After updating I lost all sounds in game, like when using seatbelt.

**Comment by am3nd01m** [comment]
All fixed now, there was a " , " missing in the fxmanifest.
