### ISSUE TITLE
bug when using aim 

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-vehiclekeys#36]
When aiming at the pistol On ped in car
There is a problem that the ped does not get out of the vehicle after handing over the key
He hits me with the car
Try while you are in front of the vehicle

**Comment by SamShanks1** [comment]
There is a config option for the chance if you get keys or the ped drives off. This isn't a bug.

Config.RobberyChance = 0.5 -- Chance to get ped keys or drive off
