### ISSUE TITLE
LockPick

### ISSUE THREAD

**Issue by rezammf** [qbcore-framework/qb-vehiclekeys#45]
Hi
When a robot car opens
All robot cars open
No need for LockPick next time
please check it
Thank you for your tireless efforts

**Comment by evanillaa** [comment]
Yes, and there is another problem
And she can make a lock pick for cars that have their keys

**Comment by evanillaa** [comment]
And another problem is
When trying to make a lock pick for the engine
Upon success, a message appears that the door has been opened

I did a test a while ago and all the problems were there
