### ISSUE TITLE
Suggestion: Whitelisting vehicles to be unlocked.

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/qb-vehiclekeys#51]
I have an AITaxiPro script, and when we call for an AI Taxi it always shows up locked and we can't get in.

This script in particular is a premium script coded with DLL Files so we can't edit it to unlock the doors when it arrives.

Was wondering if someone would be willing to code in where we can add in the config vehicle models we would like to remain unlocked indefinitely.

I'm not advanced enough to figure out how to do it unfortunately just enough to get by.

Thanks :)

**Comment by GeekHamza1** [comment]
Supported

**Comment by realtopdat** [comment]
help  have this same proble!

**Comment by Ace3412** [comment]
Yeah I still can't find an answer they say whitelist the taxi but I can't get it to work
