### ISSUE TITLE
Police Alerts

### ISSUE THREAD

**Issue by TheSilentGhost** [qbcore-framework/qb-vehiclekeys#81]
No police alerts occur whatsoever to the police when robbing vehicles from Civs. I have changed the config to 100% but the issue still occurs.

Fresh qb-vehiclekeys too

**Comment by KingRyuShin** [comment]
because in your client main at line 100 math.random() isn't set between 1 and 100

if math.random() <= chance then

**Comment by TheSilentGhost** [comment]
Nope, I changed it to: 


if math.random(1, 100) <= chance then 


and it still has not done anything

**Comment by TheSilentGhost** [comment]
> because in your client main at line 100 math.random() isn't set between 1 and 100
> 
> if math.random() <= chance then

Nope, I changed it to:

if math.random(1, 100) <= chance then

and it still has not done anything

**Comment by sony3black** [comment]
police:server:VehicleCall this function no longer exists
