### ISSUE TITLE
Lockpick issue

### ISSUE THREAD

**Issue by xc0nfig** [qbcore-framework/qb-vehiclekeys#87]
Standard lockpick won't work for me, I tried deleting the qb-lockpicks and installing it again but its still the same, meanwhile advanced lockpicks works normal, tbh no idea what to do at this point... also no errors are displayed

**Comment by JoeSzymkowiczFiveM** [comment]
Make sure you only have one instance of CreateUseableItem for lockpick in your server.

**Comment by realtopdat** [comment]
Im having this problem to Not sure where to look for CreateUseableItem
