### ISSUE TITLE
lock car

### ISSUE THREAD

**Issue by xenfovn** [qbcore-framework/qb-vehiclekeys#9]
when the player locks the car and exits the game, when they reconnect they can't open the car

**Comment by Kurosar** [comment]
Same thing happens if you take out a vehicle from your garage, you drive it for a bit, then you get out of your vehicle, you enter another player's vehicle (or a random NPC car), and then you cannot start your car anymore.

**Comment by BerkieBb** [comment]
That's because only one key at a time gets saved, it doesn't get saved to a database or a file, just kept in a table so it resets when you relog and changes when you enter another vehicle
