### ISSUE TITLE
cd_dispatch edit help?

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-vehiclekeys#95]
Could anyone help me figure out how to make alerts from car jacking use cd_dispatch for alerts? I have been trying to get it working but had no luck.

Here is a link to the install for cd_dispatch >>> https://docs.codesign.pro/paid-scripts/dispatch

I have no clue where to put the code to make it work and no one has been much help on their discord I already tried asking for help there.

**Comment by GhzGarage** [comment]
Look here https://github.com/qbcore-framework/qb-vehiclekeys/commit/757fdd0859013e45f9d432fa894f0ecb03d8bbf5

**Comment by twigmasters** [comment]
Trying to use the code you linked by copy paste replacing the code and it is giving me tons of errors. I have been able to find typos and fix some of them. However I have no clue what to with some errors because I don't understand the code. With the code on that page the resource wont even load.
