### ISSUE TITLE
Rob vehicle bug

### ISSUE THREAD

**Issue by Dersicko** [qbcore-framework/qb-vehiclekeys#96]
After done robbing the ped of his vehicle he just gets back in the car and drives off

**Comment by Andyauk** [comment]
> After done robbing the ped of his vehicle he just gets back in the car and drives off

I believe, when this update was a PR and I was testing it, the patch notes were that the driver Peds have a chance to do that, they do some interesting stuff like flipping the bird or driving over or around you, when you are carjacking lol

**Comment by ItsANoBrainer** [comment]
Yeah this is an unintended side effect of using the make ped flee native. I could not figure out exactly how to resolve this and put it as a known bug in the release notes.
