### ISSUE TITLE
Vehicles Keys issue

### ISSUE THREAD

**Issue by txdaniel55** [qbcore-framework/qb-vehiclekeys#99]
Appears when doing the /car command and the vehicle will not spawn.

[script:qb-vehiclekey] SCRIPT ERROR: @qb-vehiclekeys/server/main.lua:57: table index is nil

**Comment by Andyauk** [comment]
> Appears when doing the /car command and the vehicle will not spawn.
> 
> [script:qb-vehiclekey] SCRIPT ERROR: @qb-vehiclekeys/server/main.lua:57: table index is nil

Make sure the car isn't on your blacklisted car list, or it could be the files if using a custom made car,  that's nothing to do with qbcore, but the error I think is having issues finding citizenid. Hopefully it get fixed.

**Comment by Andyauk** [comment]
Ps if it's not a custom made car, you can use /admin and spawn vehicles there.

**Comment by ItsANoBrainer** [comment]
Doesn't look like you updated properly. Works fine fine everyone else.

**Comment by dvaturi** [comment]
> ![vehiclekeys](https://user-images.githubusercontent.com/77025615/164044299-f0b21542-8631-4f2b-b74a-655743acea7b.png) ![vehiclekeys1](https://user-images.githubusercontent.com/77025615/164044307-58deab22-3ccb-4bde-8cb2-d61f74788073.png)
> 
> I am getting this error with the new vehiclekeys and the robbing scenario doesn't fully play out. it gets this error .. it will get to the end of it and nothing happens other than the error ? Please help

having the same issue

**Comment by vaz651** [comment]
Good night I do not know why but my server is not giving key nor removing key the normal qbvehiclekeys works perfectly sera that can help me
